// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQJ3cFzGRhU2UhE4Zrj5liUk0EDg28w3Q',
    appId: '1:762992009510:web:c480fb1e4a22dbdbd8a1e7',
    messagingSenderId: '762992009510',
    projectId: 'student-uwaduh',
    authDomain: 'student-uwaduh.firebaseapp.com',
    storageBucket: 'student-uwaduh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6faORx48phrJHVakx-s8Nm2-L2jV3Hg',
    appId: '1:762992009510:android:e686cc0cef99cf9cd8a1e7',
    messagingSenderId: '762992009510',
    projectId: 'student-uwaduh',
    storageBucket: 'student-uwaduh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtAs6oK-f9bHv9msCM3wxijkcmKaa7Kv0',
    appId: '1:762992009510:ios:0b58750b0241ff59d8a1e7',
    messagingSenderId: '762992009510',
    projectId: 'student-uwaduh',
    storageBucket: 'student-uwaduh.appspot.com',
    iosClientId: '762992009510-24sbct5d4r4sf8a7994c0katbukhube2.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtAs6oK-f9bHv9msCM3wxijkcmKaa7Kv0',
    appId: '1:762992009510:ios:0b58750b0241ff59d8a1e7',
    messagingSenderId: '762992009510',
    projectId: 'student-uwaduh',
    storageBucket: 'student-uwaduh.appspot.com',
    iosClientId: '762992009510-24sbct5d4r4sf8a7994c0katbukhube2.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentapp',
  );
}
